# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from src.communication_structs.base_model_ import Model
from src.communication_structs.state import State  # noqa: F401,E501
from src.routes import util


class City(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, state: State=None):  # noqa: E501
        """City - a model defined in Swagger

        :param id: The id of this City.  # noqa: E501
        :type id: int
        :param name: The name of this City.  # noqa: E501
        :type name: str
        :param state: The state of this City.  # noqa: E501
        :type state: State
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'state': State
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'state': 'state'
        }
        self._id = id
        self._name = name
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'City':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The City of this City.  # noqa: E501
        :rtype: City
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this City.

        Id of City  # noqa: E501

        :return: The id of this City.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this City.

        Id of City  # noqa: E501

        :param id: The id of this City.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this City.

        name of City  # noqa: E501

        :return: The name of this City.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this City.

        name of City  # noqa: E501

        :param name: The name of this City.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def state(self) -> State:
        """Gets the state of this City.


        :return: The state of this City.
        :rtype: State
        """
        return self._state

    @state.setter
    def state(self, state: State):
        """Sets the state of this City.


        :param state: The state of this City.
        :type state: State
        """

        self._state = state
